#!/bin/bash -x

numactl --physcpubind=2-13 --membind=0 /usr/bin/qemu-system-x86_64 -enable-kvm \
-name vth-107-numa-0 -M pc -daemonize --enable-kvm -cpu host -smp 12 -m 16G  \
-numa node,memdev=mem -mem-prealloc \
-object memory-backend-file,id=mem,size=16G,mem-path=/dev/hugepages,share=on \
-serial telnet:127.0.0.1:10700,server,nowait,nodelay \
-netdev tap,id=hostnet0,ifname=tapMGMT10 \
-device e1000,netdev=hostnet0,id=net0,mac=60:00:01:07:00:10 \
-chardev socket,id=char1,path=/usr/local/var/run/openvswitch/vhost-bond5 \
-netdev type=vhost-user,id=mynet1,chardev=char1,vhostforce \
-device virtio-net-pci,mac=60:00:01:07:00:01,netdev=mynet1 \
-chardev socket,id=char2,path=/usr/local/var/run/openvswitch/vhost-bond6 \
-netdev type=vhost-user,id=mynet2,chardev=char2,vhostforce \
-device virtio-net-pci,mac=60:00:01:07:00:02,netdev=mynet2 \
-chardev socket,id=char3,path=/usr/local/var/run/openvswitch/vhost-bond7 \
-netdev type=vhost-user,id=mynet3,chardev=char3,vhostforce \
-device virtio-net-pci,mac=60:00:01:07:00:03,netdev=mynet3 \
-chardev socket,id=char4,path=/usr/local/var/run/openvswitch/vhost-bond8 \
-netdev type=vhost-user,id=mynet4,chardev=char4,vhostforce \
-device virtio-net-pci,mac=60:00:01:07:00:04,netdev=mynet4 \
-vnc 127.0.0.1:1070 \
-boot order=dc,menu=on \
-uuid 4a9b3f53-fa2a-47f3-a757-dd87720d9d1d \
-drive file=/home/libvirt-qemu/images/vth-107-numa-0.qcow2,if=virtio,format=qcow2,index=0,media=disk

brctl addif br105 tapMGMT10

